name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Test Runner
        run: |
          echo "===== Runner Test ====="
          whoami
          pwd
          hostname
          date
          ls -la /home/user1/Doan
