name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy on Ubuntu
        run: |
          cd /home/user1/Doan

          echo "Current directory:"
          pwd

          echo "Pull newest code..."
          git pull origin main

          echo "Rebuild Docker..."
          docker compose up -d --build

          echo "Running containers:"
          docker ps
